Added two new tests to Archive & Unarchive locations
dimagi/dimagi-qa pull request #109
Opened 2022-06-14 11:32 UTC by nsaxena03

As part of fix #5, we have to add the tests to for the following workflows:

- Archive & Unarchive Locations 
- Download & Upload Web Users

Creating a PR for review for Archive & Unarchive location tests added.

2022-06-15 08:44 UTC, kiran-tripathy commented on HQSmokeTests/testPages/users/org_structure_page.py
> +        assert archived_loc == active_loc, "Location is not Archived"
What are we checking here, the text of the location archived shouldn't be changed after being archived?

It's a good check to add, but then we should be marking this test case as pass if:
1. the location is present on the archived page
 This is checked here I believe ` self.is_present_and_displayed(self.archive_this_loc)`
2. NOT present on the landing page2. 
But do we check this?

2022-06-15 08:44 UTC, kiran-tripathy commented on HQSmokeTests/testPages/users/org_structure_page.py
> +        assert archived_loc == active_loc, "Location is not Archived"
What are we checking here, the text of the location archived shouldn't be changed after being archived?

It's a good check to add, but then we should be marking this test case as pass if:
1. the location is present on the archived page
 This is checked here I believe ` self.is_present_and_displayed(self.archive_this_loc)`
2. NOT present on the landing page2. 
But do we check this?

2022-06-15 08:45 UTC, kiran-tripathy commented on HQSmokeTests/testPages/users/org_structure_page.py
> +        assert unarchived_loc == archived_loc, "Location not unarchived successfully"
Same, we should pass when vice-versa of [this](https://github.com/dimagi/dimagi-qa/pull/109/files#r897706390) is true.

2022-06-15 08:45 UTC, kiran-tripathy commented on HQSmokeTests/testPages/users/org_structure_page.py
> +        assert unarchived_loc == archived_loc, "Location not unarchived successfully"
Same, we should pass when vice-versa of [this](https://github.com/dimagi/dimagi-qa/pull/109/files#r897706390) is true.

2022-06-15 08:48 UTC, kiran-tripathy requested changes
I've suggested some changes, once they're addressed we should be good. Also a quick check- Has this been tested both on prod and staging?

2022-06-17 10:23 UTC, nsaxena03 commented
Hi @kiran-tripathy , I have added the remaining following tests 

- Download/ Upload Web Users
- Creation of Dedupe Cases rule
- Upload and Download Data Dictionary 

And have also made changes to the Archive and Unarchvie locations as per your feedback.

2022-06-17 11:19 UTC, kiran-tripathy approved these changes

2022-06-17 11:23 UTC, kiran-tripathy commented
I added Kankana to review this, just skimmed over -- If works on CI as well, we can merge this.

2022-06-17 12:33 UTC, merged