Case search workflows
dimagi/dimagi-qa pull request #152
Opened 2022-09-12 11:13 UTC by kiran-tripathy

## Summary
Added Case Search Workflows

## Description

[Case Search Regression Plan](https://docs.google.com/spreadsheets/d/1sPLEAJFlhztZ656TH4jk-tjUbhu_YE-8dvVdgiy3xQQ/edit#gid=1311275056&range=F5)

### Link to Jira Ticket (if applicable)
[https://dimagi-dev.atlassian.net/browse/QA-4182](https://dimagi-dev.atlassian.net/browse/QA-4182)

## QA Checklist

- [ ] Label(s) and Assignee added
- [ ] PR sent for review
- [ ] Documentation (if applicable) added/updated

2022-09-12 14:15 UTC, kbo001 requested changes

2022-09-13 08:26 UTC, kiran-tripathy commented on Features/CaseSearch/test_cases/conftest.py
> +                DIMAGIQA_MAIL_PASSWORD
https://github.com/dimagi/dimagi-qa/pull/152/commits/7b88b6b0b4793c1cbf3ed350b11a772d49940367

2022-09-13 08:27 UTC, kiran-tripathy commented on Features/CaseSearch/test_cases/test_01_caseseach_workflows.py
> +    webapps.submit_the_form()
https://github.com/dimagi/dimagi-qa/pull/152/commits/40f3e454cf359736ad4fcaeaf2df216df5595f8f

2022-09-13 08:27 UTC, kiran-tripathy commented on Features/CaseSearch/test_cases/test_01_caseseach_workflows.py
> +    webapps.submit_the_form()
https://github.com/dimagi/dimagi-qa/pull/152/commits/40f3e454cf359736ad4fcaeaf2df216df5595f8f

2022-09-13 08:27 UTC, kiran-tripathy commented on Features/CaseSearch/test_cases/test_01_caseseach_workflows.py
> +    webapps.search_all_cases()
https://github.com/dimagi/dimagi-qa/pull/152/commits/40f3e454cf359736ad4fcaeaf2df216df5595f8f

2022-09-13 13:31 UTC, kbo001 approved these changes
approved

2022-09-14 12:10 UTC, merged